version: '3'

services:
  app:
    image: "llmops-app"
    container_name: llmops-app
    build: 
      context: .
      dockerfile: docker/Dockerfile
    # working_dir: /app
    ports:
      - "8045:8045"
    environment:
      - MODEL_PATH=/models/microsoft/Phi-3-mini-4k-instruct
      - DATABASE_URL=postgresql://user:password@db/dbname
    env_file:
      - .env
    volumes:
      - /space/hotel/phit/projects/LLMOps/models/microsoft/Phi-3-mini-4k-instruct:/models/microsoft/Phi-3-mini-4k-instruct
      - .:/app
    # command: [ "/bin/bash", "-c", "ls", "la" ]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
